name: pre-merge-checks
on:
  pull_request:
    branches: [main, develop]
jobs:
  Lint-Check:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run env-check
        env:
          KEY: ${{secrets.KEY}}
